### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by asyncanup** [hayd/deno_docker#3]
```
Compiling file:///app/main.ts
Downloading https://deno.land/std/net/http.ts
thread 'tokio-runtime-worker-1' panicked at 'assertion failed: result.is_some()', ../../cli/compiler.rs:145:3
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Uncaught NotFound: Cannot resolve module "https://deno.land/std/net/http.ts" from "/app/main.ts"
    at DenoError (deno/js/errors.ts:22:5)
    at maybeError (deno/js/errors.ts:33:12)
    at maybeThrowError (deno/js/errors.ts:39:15)
    at sendSync (deno/js/dispatch.ts:82:5)
    at fetchModuleMetaData (deno/js/os.ts:75:19)
    at _resolveModule (deno/js/compiler.ts:249:38)
    at resolveModuleNames (deno/js/compiler.ts:479:35)
    at compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:118650:138)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:86767:127)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:87001:24)thread '
tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', src/libcore/result.rs:997:5
```

**Comment by bartlomieju** [comment]
There were a lot of changes in Deno recently, @hayd can you update images to work with Deno v0.4.0?

**Comment by hayd** [comment]
@asyncanup 0.4 should be available now, which hopefully will fix?

**Comment by hayd** [comment]
I also updated the run entry points and tested the Dockerfile in /examples which seems to work now (after a couple of edits). Apologies for not keeping that up to date!

@asyncanup  that is the issue above (although the error is a little gnarly), `https://deno.land/std/net/http.ts` is now/should be `https://deno.land/std/http/server.ts`.
